language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -y install python2 python-pip
  - python2 -m pip install --user google-apis-client-generator
install:
  - ./gradlew classes testClasses
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
