dist: xenial
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -y install python2.7 python-pip
  - python2 -m pip install --user google-apis-client-generator
install:
 - JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew classes testClasses
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
